# Generated by Django 5.2.3 on 2025-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='race',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
