# Generated by Django 5.2.3 on 2025-06-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('clean', 'Clean')], default='classic', max_length=20),
        ),
    ]
