# Generated by Django 5.2.3 on 2025-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('professional', 'Professional'), ('modern', 'Modern'), ('simple', 'Simple')], default='classic', max_length=20),
        ),
    ]
