# Generated by Django 5.2.3 on 2025-06-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_rename_certifications_resume_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='responsibilities',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=255, verbose_name='Degree / Certification / Course'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description (optional)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=255, verbose_name='School / Program / Training Name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.resume'),
        ),
    ]
