# Generated by Django 5.2.3 on 2025-06-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_rename_responsibilities_experience_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='website',
        ),
    ]
