# Generated by Django 5.2.3 on 2025-07-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_alter_skill_name_alter_skill_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume'),
        ),
    ]
