# Generated by Django 5.2.3 on 2025-07-02 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_skill_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='resumes.resume'),
        ),
    ]
