# Generated by Django 5.2.3 on 2025-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_remove_contactinfo_location_contactinfo_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill_summary',
            field=models.TextField(blank=True),
        ),
    ]
