# Generated by Django 5.2.3 on 2025-08-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_application_applicant_remove_application_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
